name: otraku
description: An unofficial AniList app.

publish_to: 'none'

version: 1.0.8+16

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  get: ^4.1.4
  get_storage: ^2.0.2
  flutter_secure_storage: ^4.2.0
  url_launcher: ^6.0.3
  app_links: ^2.1.0
  workmanager: ^0.4.0
  flutter_local_notifications: ^5.0.0+4
  markdown: ^4.0.0
  flutter_widget_from_html_core: ^0.6.1+1
  ionicons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/ios.png"
  adaptive_icon_background: "#0F171E"
  adaptive_icon_foreground: "assets/icons/android.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/about_icon.png

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500